### ISSUE TITLE
raft节点switch over后共识panic

### ISSUE THREAD

**Issue by rink1969** [cita-cloud/consensus_raft#69]
```
2022-11-16 06:06:12	
============================
2022-11-16 06:06:12	
Thread main panicked at to_commit 1220 is out of range [last_index 1219], raft_id: 1404849201612882401, module: raft::util:106, /usr/local/cargo/git/checkouts/raft-rs-7f6e0c0a0460e1b4/7063700/src/[raft_log.rs:292](http://raft_log.rs:292/)
2022-11-16 06:06:12	
position:
2022-11-16 06:06:12	
2022-11-16 06:06:12	
2022-11-16 06:06:12	
  22: _start
2022-11-16 06:06:12	
  21: __libc_start_main
2022-11-16 06:06:12	
  20: main
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[rt.rs:148](http://rt.rs:148/):20
2022-11-16 06:06:12	
      std::rt::lang_start_internal
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panic.rs:137](http://panic.rs:137/):14
2022-11-16 06:06:12	
      std::panic::catch_unwind
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19
2022-11-16 06:06:12	
      std::panicking::try
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40
2022-11-16 06:06:12	
      std::panicking::try::do_call
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[rt.rs:148](http://rt.rs:148/):48
2022-11-16 06:06:12	
      std::rt::lang_start_internal::{{closure}}
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panic.rs:137](http://panic.rs:137/):14
2022-11-16 06:06:12	
      std::panic::catch_unwind
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:456](http://panicking.rs:456/):19
2022-11-16 06:06:12	
      std::panicking::try
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:492](http://panicking.rs:492/):40
2022-11-16 06:06:12	
      std::panicking::try::do_call
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/[function.rs:283](http://function.rs:283/):13
2022-11-16 06:06:12	
  19: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
2022-11-16 06:06:12	
  18: std::rt::lang_start::{{closure}}
2022-11-16 06:06:12	
  17: std::sys_common::backtrace::__rust_begin_short_backtrace
2022-11-16 06:06:12	
  16: consensus::main
2022-11-16 06:06:12	
  15: tokio::runtime::Runtime::block_on
2022-11-16 06:06:12	
  14: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
2022-11-16 06:06:12	
  13: tokio::park::thread::CachedParkThread::block_on
2022-11-16 06:06:12	
  12: std::thread::local::LocalKey<T>::with
2022-11-16 06:06:12	
  11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
2022-11-16 06:06:12	
  10: consensus::peer::Peer::run::{{closure}}
2022-11-16 06:06:12	
   9: raft::raw_node::RawNode<T>::step
2022-11-16 06:06:12	
   8: raft::raft::Raft<T>::step
2022-11-16 06:06:12	
   7: raft::raft::Raft<T>::handle_heartbeat
2022-11-16 06:06:12	
   6: raft::raft_log::RaftLog<T>::commit_to
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/[panicking.rs:142](http://panicking.rs:142/):14
2022-11-16 06:06:12	
   5: core::panicking::panic_fmt
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:584](http://panicking.rs:584/):5
2022-11-16 06:06:12	
   4: rust_begin_unwind
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/[backtrace.rs:138](http://backtrace.rs:138/):18
2022-11-16 06:06:12	
   3: std::sys_common::backtrace::__rust_end_short_backtrace
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:588](http://panicking.rs:588/):13
2022-11-16 06:06:12	
   2: std::panicking::begin_panic_handler::{{closure}}
2022-11-16 06:06:12	
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/[panicking.rs:702](http://panicking.rs:702/):17
2022-11-16 06:06:12	
   1: std::panicking::rust_panic_with_hook
2022-11-16 06:06:12	
   0: consensus::utils::set_panic_handler::{{closure}}
2022-11-16 06:06:12	
============================
2022-11-16 06:06:12	
Nov 15 22:06:12.999 ERRO 
2022-11-16 06:06:12	
Nov 15 22:06:12.695 INFO RawNode created with id 1404849201612882401., id: 1404849201612882401, raft_id: 1404849201612882401, module: raft::raw_node:315
```

**Comment by rink1969** [comment]
可能是交换两个raft节点身份之前，两个节点的日志进度有差异。
交换之后，leader还是按照之前的进度来发送日志，导致index不连续。

建议先将要交换身份的raft节点剔除出共识列表，然后再操作。
需要进一步完善守护节点方案。

**Comment by rink1969** [comment]
v6.6.2版本bft链也会有类似的问题。
一个共识节点（node0）和一个只读节点（node4）switchover之后，两个节点都正常。
但是如果通过重新apply的方式换回原来的节点账户，原有的共识节点（node0）有的时候会不同步，不出块。
一方面是 https://github.com/cita-cloud/controller/issues/189  （node4可以收到node0的CSI，但是因为前面的bug，它不会回应）。
另一方面，似乎是账号切换导致zenoh的路由混乱，网络不同。node1和node2压根就没收到node0的CSI。

**Comment by rink1969** [comment]
network原本使用了node address来做zenoh的id，改为使用domain哈希后用做zenoh的id标识，解决后一个问题。
https://github.com/cita-cloud/network_zenoh/pull/16

**Comment by rink1969** [comment]
network修改之后，bft和overlord的switch over没有问题了。
raft保险起见，还是先将节点剔除出共识列表，然后再操作。
